EXE = main.exe

LIB = 

INCLUDE_DIRS = $(ROOT)/code/linearStack/inc \
			   $(ROOT)/code/linkStack/inc \
			   $(ROOT)/code/digitConv/inc \
			   $(ROOT)/code/verifyBrackets/inc \
			   $(ROOT)/code/lineEditor/inc \
			   $(ROOT)/code/mazePath/inc \
			   $(ROOT)/code/hanoi/inc \
			   $(ROOT)/code/linkQueue/inc \
			   $(ROOT)/../

LINK_LIBS = linearStack linkStack digitConv verifyBrackets lineEditor \
			mazePath hanoi linkQueue

include $(ROOT)/build/make.rule

